### ISSUE TITLE
Cannot read footnotes

### ISSUE THREAD

**Issue by alramalho** [allenai/s2orc-doc2json#28]
First of all thanks for open-sourcing this helpful tool. 
I was using it for personal research and found that it is not properly working when papers contain footnotes. When reading the paper about [CheXpert](https://www.semanticscholar.org/reader/89a816719613e220a64ab2590c938c23bbfe187e), the json conversion did not contain the important footnote present in the introduction:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/47791391/207070588-389f2d53-20e0-4645-bbc8-ca472dafa76b.png">

Are you aware of this issue? If so, will it be tackled at some point?
Thank you

**Comment by lfoppiano** [comment]
@alramalho to be precise this is not a footnote, this is the copyright statement. This information goes in the header (at least for what concern Grobid).  
Do you need the copyright information?

**Comment by alramalho** [comment]
hey @lfoppiano, actually what I need is the [1] reference link, which I couldn't find anywhere in the JSON output file

**Comment by lfoppiano** [comment]
Hi @alramalho, this is a special case where grobid recognise it incorrectly the link as the copyright statement. 
It'a rather difficult case because the copyright usually comes with a link in the statement. 


The optimal solution is that we add this document as training data with the correct segmentation. However, despite the authors shared on arxiv (https://arxiv.org/abs/1901.07031) as "CC-BY" I'd say we won't be able to use it. 

I've opened a new issue on grobid, that you can follow: https://github.com/kermitt2/grobid/issues/1048.

**Comment by alramalho** [comment]
That makes sense, I'll follow it there then, closing the issue :) Thanks!
